<?php
/**
 * @file
 * openacademy_core_democontent.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function openacademy_core_democontent_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: menu-footer-menu:about
  $menu_links['menu-footer-menu:about'] = array(
    'menu_name' => 'menu-footer-menu',
    'link_path' => 'about',
    'router_path' => 'about',
    'link_title' => 'About',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '0',
  );
  // Exported menu link: menu-footer-menu:contact
  $menu_links['menu-footer-menu:contact'] = array(
    'menu_name' => 'menu-footer-menu',
    'link_path' => 'contact',
    'router_path' => 'contact',
    'link_title' => 'Contact',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '0',
  );
  // Translatables
  // Included for use with string extractors like potx.
  t('About');
  t('Contact');


  return $menu_links;
}
